<a href="https://colab.research.google.com/github/SANDESHAHAHA/Data_Science/blob/main/Gradient_descent.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from tensorflow import keras

In [2]:
df=pd.read_csv("/content/insurance_data.csv")

In [3]:
df.head()

   age  affordibility  bought_insurance
0   22              1                 0
1   25              0                 0
2   47              1                 1
3   52              0                 0
4   46              1                 1

In [4]:
df.shape

(28, 3)

In [5]:
df.isnull().sum()

age                 0
affordibility       0
bought_insurance    0
dtype: int64

In [6]:
from sklearn.model_selection import train_test_split

In [7]:
X_train,X_test,y_train,y_test=train_test_split(df[['affordibility','age']],df.bought_insurance,test_size=0.2,random_state=25)

In [8]:
len(X_train)

22

In [9]:
len(X_test)

6

In [10]:
X_train

    affordibility  age
0               1   22
13              0   29
6               0   55
17              1   58
24              1   50
19              1   18
25              1   54
16              0   25
20              1   21
3               0   52
7               0   60
1               0   25
5               1   56
27              1   46
8               1   62
18              0   19
12              0   27
23              1   45
22              1   40
15              1   55
26              1   23
4               1   46

In [11]:
X_train_scaled=X_train.copy()
X_train_scaled['age']=X_train_scaled['age']/100

X_test_scaled=X_test.copy()
X_test_scaled['age']=X_test_scaled['age']/100

In [12]:
X_train_scaled

    affordibility   age
0               1  0.22
13              0  0.29
6               0  0.55
17              1  0.58
24              1  0.50
19              1  0.18
25              1  0.54
16              0  0.25
20              1  0.21
3               0  0.52
7               0  0.60
1               0  0.25
5               1  0.56
27              1  0.46
8               1  0.62
18              0  0.19
12              0  0.27
23              1  0.45
22              1  0.40
15              1  0.55
26              1  0.23
4               1  0.46

In [13]:
model=keras.Sequential([
    keras.layers.Dense(1,input_shape=(2,),activation='sigmoid',kernel_initializer='ones',bias_initializer='zeros')
    #they are just weight and bias if you dont initialize the parameters it wont be problem at all the built in function in tf will automatically decide those parameters.

])
model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])
model.fit(X_train_scaled,y_train,epochs=5000)

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Streaming output truncated to the last 5000 lines.
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 62ms/step - accuracy: 0.7273 - loss: 0.5321
Epoch 2502/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - accuracy: 0.7273 - loss: 0.5321
Epoch 2503/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - accuracy: 0.7273 - loss: 0.5321
Epoch 2504/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 135ms/step - accuracy: 0.7273 - loss: 0.5320
Epoch 2505/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 63ms/step - accuracy: 0.7273 - loss: 0.5320
Epoch 2506/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 0.7273 - loss: 0.5320
Epoch 2507/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 65ms/step - accuracy: 0.7273 - loss: 0.5319
Epoch 2508/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 62ms/step - accuracy: 0.7273 - loss: 0.5319
Epoch 2509/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - accuracy: 0.7273 - loss: 0.5318
Epoch 2510/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - accuracy: 0.7273 - loss: 0.5318
Epoch 2511/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - accuracy: 0.7273 - loss: 0.5318
Epoch 2512/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - accuracy: 0.7273 - loss: 0.5317
Epoch 2513/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - accuracy: 0.7273 - loss: 0.5317
Epoch 2514/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 0.7273 - loss: 0.5316
Epoch 2515/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - accuracy: 0.7273 - loss: 0.5316
Epoch 2516/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - accuracy: 0.7273 - loss: 0.5316
Epoch 2517/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.7273 - loss: 0.5315
Epoch 2518/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 0.7273 - loss: 0.5315
Epoch 2519/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 72ms/step - accuracy: 0.7273 - loss: 0.5315
Epoch 2520/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 129ms/step - accuracy: 0.7273 - loss: 0.5314
Epoch 2521/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - accuracy: 0.7273 - loss: 0.5314
Epoch 2522/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 0.7273 - loss: 0.5313
Epoch 2523/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 0.7273 - loss: 0.5313
Epoch 2524/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 0.7273 - loss: 0.5313
Epoch 2525/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - accuracy: 0.7273 - loss: 0.5312
Epoch 2526/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.7273 - loss: 0.5312
Epoch 2527/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - accuracy: 0.7273 - loss: 0.5311
Epoch 2528/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - accuracy: 0.7273 - loss: 0.5311
Epoch 2529/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 0.7273 - loss: 0.5311
Epoch 2530/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - accuracy: 0.7273 - loss: 0.5310
Epoch 2531/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 0.7273 - loss: 0.5310
Epoch 2532/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step - accuracy: 0.7273 - loss: 0.5310
Epoch 2533/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - accuracy: 0.7273 - loss: 0.5309
Epoch 2534/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - accuracy: 0.7273 - loss: 0.5309
Epoch 2535/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - accuracy: 0.7273 - loss: 0.5308
Epoch 2536/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 143ms/step - accuracy: 0.7273 - loss: 0.5308
Epoch 2537/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - accuracy: 0.7273 - loss: 0.5308
Epoch 2538/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 0.7273 - loss: 0.5307
Epoch 2539/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 0.7273 - loss: 0.5307
Epoch 2540/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 65ms/step - accuracy: 0.7273 - loss: 0.5307
Epoch 2541/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - accuracy: 0.7273 - loss: 0.5306
Epoch 2542/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.7273 - loss: 0.5306
Epoch 2543/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.7273 - loss: 0.5305
Epoch 2544/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 65ms/step - accuracy: 0.7273 - loss: 0.5305
Epoch 2545/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - accuracy: 0.7273 - loss: 0.5305
Epoch 2546/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.7273 - loss: 0.5304
Epoch 2547/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - accuracy: 0.7273 - loss: 0.5304
Epoch 2548/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - accuracy: 0.7273 - loss: 0.5303
Epoch 2549/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 0.7273 - loss: 0.5303
Epoch 2550/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - accuracy: 0.7273 - loss: 0.5303
Epoch 2551/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - accuracy: 0.7273 - loss: 0.5302
Epoch 2552/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 67ms/step - accuracy: 0.7273 - loss: 0.5302
Epoch 2553/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 139ms/step - accuracy: 0.7273 - loss: 0.5302
Epoch 2554/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 128ms/step - accuracy: 0.7273 - loss: 0.5301
Epoch 2555/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - accuracy: 0.7273 - loss: 0.5301
Epoch 2556/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 0.7273 - loss: 0.5300
Epoch 2557/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 63ms/step - accuracy: 0.7273 - loss: 0.5300
Epoch 2558/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - accuracy: 0.7273 - loss: 0.5300
Epoch 2559/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 62ms/step - accuracy: 0.7273 - loss: 0.5299
Epoch 2560/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 67ms/step - accuracy: 0.7273 - loss: 0.5299
Epoch 2561/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - accuracy: 0.7273 - loss: 0.5299
Epoch 2562/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - accuracy: 0.7273 - loss: 0.5298
Epoch 2563/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 0.7273 - loss: 0.5298
Epoch 2564/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step - accuracy: 0.7273 - loss: 0.5297
Epoch 2565/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - accuracy: 0.7273 - loss: 0.5297
Epoch 2566/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 135ms/step - accuracy: 0.7273 - loss: 0.5297
Epoch 2567/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - accuracy: 0.7273 - loss: 0.5296
Epoch 2568/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step - accuracy: 0.7273 - loss: 0.5296
Epoch 2569/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 143ms/step - accuracy: 0.7273 - loss: 0.5295
Epoch 2570/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 133ms/step - accuracy: 0.7273 - loss: 0.5295
Epoch 2571/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.7273 - loss: 0.5295
Epoch 2572/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - accuracy: 0.7273 - loss: 0.5294
Epoch 2573/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - accuracy: 0.7273 - loss: 0.5294
Epoch 2574/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - accuracy: 0.7273 - loss: 0.5294
Epoch 2575/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - accuracy: 0.7273 - loss: 0.5293
Epoch 2576/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - accuracy: 0.7273 - loss: 0.5293
Epoch 2577/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - accuracy: 0.7273 - loss: 0.5292
Epoch 2578/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - accuracy: 0.7273 - loss: 0.5292
Epoch 2579/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - accuracy: 0.7273 - loss: 0.5292
Epoch 2580/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 62ms/step - accuracy: 0.7273 - loss: 0.5291
Epoch 2581/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - accuracy: 0.7273 - loss: 0.5291
Epoch 2582/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - accuracy: 0.7273 - loss: 0.5291
Epoch 2583/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - accuracy: 0.7273 - loss: 0.5290
Epoch 2584/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step - accuracy: 0.7273 - loss: 0.5290
Epoch 2585/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - accuracy: 0.7273 - loss: 0.5289
Epoch 2586/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - accuracy: 0.7273 - loss: 0.5289
Epoch 2587/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 0.7273 - loss: 0.5289
Epoch 2588/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 74ms/step - accuracy: 0.7273 - loss: 0.5288
Epoch 2589/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 75ms/step - accuracy: 0.7273 - loss: 0.5288
Epoch 2590/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 148ms/step - accuracy: 0.7273 - loss: 0.5288
Epoch 2591/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 73ms/step - accuracy: 0.7273 - loss: 0.5287
Epoch 2592/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 78ms/step - accuracy: 0.7273 - loss: 0.5287
Epoch 2593/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 150ms/step - accuracy: 0.7273 - loss: 0.5286
Epoch 2594/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 123ms/step - accuracy: 0.7273 - loss: 0.5286
Epoch 2595/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 145ms/step - accuracy: 0.7273 - loss: 0.5286
Epoch 2596/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 138ms/step - accuracy: 0.7273 - loss: 0.5285
Epoch 2597/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 144ms/step - accuracy: 0.7273 - loss: 0.5285
Epoch 2598/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 131ms/step - accuracy: 0.7273 - loss: 0.5285
Epoch 2599/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 99ms/step - accuracy: 0.7273 - loss: 0.5284
Epoch 2600/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 142ms/step - accuracy: 0.7273 - loss: 0.5284
Epoch 2601/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 131ms/step - accuracy: 0.7273 - loss: 0.5283
Epoch 2602/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 127ms/step - accuracy: 0.7273 - loss: 0.5283
Epoch 2603/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 143ms/step - accuracy: 0.7273 - loss: 0.5283
Epoch 2604/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 129ms/step - accuracy: 0.7273 - loss: 0.5282
Epoch 2605/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 74ms/step - accuracy: 0.7273 - loss: 0.5282
Epoch 2606/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 165ms/step - accuracy: 0.7273 - loss: 0.5282
Epoch 2607/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 119ms/step - accuracy: 0.7273 - loss: 0.5281
Epoch 2608/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 144ms/step - accuracy: 0.7273 - loss: 0.5281
Epoch 2609/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 126ms/step - accuracy: 0.7273 - loss: 0.5280
Epoch 2610/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 80ms/step - accuracy: 0.7273 - loss: 0.5280
Epoch 2611/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 134ms/step - accuracy: 0.7273 - loss: 0.5280
Epoch 2612/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 130ms/step - accuracy: 0.7273 - loss: 0.5279
Epoch 2613/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - accuracy: 0.7273 - loss: 0.5279
Epoch 2614/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - accuracy: 0.7273 - loss: 0.5279
Epoch 2615/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - accuracy: 0.7273 - loss: 0.5278
Epoch 2616/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - accuracy: 0.7273 - loss: 0.5278
Epoch 2617/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - accuracy: 0.7273 - loss: 0.5277
Epoch 2618/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - accuracy: 0.7273 - loss: 0.5277
Epoch 2619/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.7273 - loss: 0.5277
Epoch 2620/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - accuracy: 0.7273 - loss: 0.5276
Epoch 2621/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - accuracy: 0.7273 - loss: 0.5276
Epoch 2622/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 0.7273 - loss: 0.5276
Epoch 2623/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 0.7273 - loss: 0.5275
Epoch 2624/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 138ms/step - accuracy: 0.7273 - loss: 0.5275
Epoch 2625/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - accuracy: 0.7273 - loss: 0.5274
Epoch 2626/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - accuracy: 0.7273 - loss: 0.5274
Epoch 2627/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - accuracy: 0.7273 - loss: 0.5274
Epoch 2628/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - accuracy: 0.7273 - loss: 0.5273
Epoch 2629/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 66ms/step - accuracy: 0.7273 - loss: 0.5273
Epoch 2630/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 0.7273 - loss: 0.5273
Epoch 2631/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 65ms/step - accuracy: 0.7273 - loss: 0.5272
Epoch 2632/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - accuracy: 0.7273 - loss: 0.5272
Epoch 2633/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - accuracy: 0.7273 - loss: 0.5271
Epoch 2634/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - accuracy: 0.7273 - loss: 0.5271
Epoch 2635/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - accuracy: 0.7273 - loss: 0.5271
Epoch 2636/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.7273 - loss: 0.5270
Epoch 2637/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - accuracy: 0.7273 - loss: 0.5270
Epoch 2638/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 67ms/step - accuracy: 0.7273 - loss: 0.5270
Epoch 2639/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - accuracy: 0.7273 - loss: 0.5269
Epoch 2640/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 64ms/step - accuracy: 0.7273 - loss: 0.5269
Epoch 2641/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - accuracy: 0.7273 - loss: 0.5268
Epoch 2642/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - accuracy: 0.7727 - loss: 0.5268
Epoch 2643/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step - accuracy: 0.7727 - loss: 0.5268
Epoch 2644/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 0.7727 - loss: 0.5267
Epoch 2645/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 64ms/step - accuracy: 0.7727 - loss: 0.5267
Epoch 2646/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - accuracy: 0.7727 - loss: 0.5267
Epoch 2647/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 64ms/step - accuracy: 0.7727 - loss: 0.5266
Epoch 2648/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 0.7727 - loss: 0.5266
Epoch 2649/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - accuracy: 0.7727 - loss: 0.5265
Epoch 2650/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - accuracy: 0.7727 - loss: 0.5265
Epoch 2651/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 0.7727 - loss: 0.5265
Epoch 2652/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.7727 - loss: 0.5264
Epoch 2653/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 62ms/step - accuracy: 0.7727 - loss: 0.5264
Epoch 2654/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step - accuracy: 0.7727 - loss: 0.5264
Epoch 2655/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 143ms/step - accuracy: 0.7727 - loss: 0.5263
Epoch 2656/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 127ms/step - accuracy: 0.7727 - loss: 0.5263
Epoch 2657/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - accuracy: 0.7727 - loss: 0.5263
Epoch 2658/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 0.7727 - loss: 0.5262
Epoch 2659/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - accuracy: 0.7727 - loss: 0.5262
Epoch 2660/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - accuracy: 0.7727 - loss: 0.5261
Epoch 2661/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - accuracy: 0.7727 - loss: 0.5261
Epoch 2662/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 146ms/step - accuracy: 0.7727 - loss: 0.5261
Epoch 2663/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - accuracy: 0.7727 - loss: 0.5260
Epoch 2664/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 0.7727 - loss: 0.5260
Epoch 2665/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - accuracy: 0.7727 - loss: 0.5260
Epoch 2666/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 0.7727 - loss: 0.5259
Epoch 2667/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step - accuracy: 0.7727 - loss: 0.5259
Epoch 2668/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 0.7727 - loss: 0.5258
Epoch 2669/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - accuracy: 0.7727 - loss: 0.5258
Epoch 2670/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - accuracy: 0.7727 - loss: 0.5258
Epoch 2671/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 67ms/step - accuracy: 0.7727 - loss: 0.5257
Epoch 2672/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - accuracy: 0.7727 - loss: 0.5257
Epoch 2673/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - accuracy: 0.7727 - loss: 0.5257
Epoch 2674/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 65ms/step - accuracy: 0.7727 - loss: 0.5256
Epoch 2675/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 0.7727 - loss: 0.5256
Epoch 2676/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.7727 - loss: 0.5256
Epoch 2677/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - accuracy: 0.7727 - loss: 0.5255
Epoch 2678/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - accuracy: 0.7727 - loss: 0.5255
Epoch 2679/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 65ms/step - accuracy: 0.7727 - loss: 0.5254
Epoch 2680/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - accuracy: 0.7727 - loss: 0.5254
Epoch 2681/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 0.7727 - loss: 0.5254
Epoch 2682/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 0.7727 - loss: 0.5253
Epoch 2683/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.7727 - loss: 0.5253
Epoch 2684/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.7727 - loss: 0.5253
Epoch 2685/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - accuracy: 0.7727 - loss: 0.5252
Epoch 2686/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 0.7727 - loss: 0.5252
Epoch 2687/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.7727 - loss: 0.5251
Epoch 2688/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 73ms/step - accuracy: 0.7727 - loss: 0.5251
Epoch 2689/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 73ms/step - accuracy: 0.7727 - loss: 0.5251
Epoch 2690/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 0.7727 - loss: 0.5250
Epoch 2691/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 0.7727 - loss: 0.5250
Epoch 2692/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - accuracy: 0.7727 - loss: 0.5250
Epoch 2693/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 0.7727 - loss: 0.5249
Epoch 2694/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 0.7727 - loss: 0.5249
Epoch 2695/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - accuracy: 0.7727 - loss: 0.5249
Epoch 2696/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - accuracy: 0.7727 - loss: 0.5248
Epoch 2697/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 66ms/step - accuracy: 0.7727 - loss: 0.5248
Epoch 2698/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 0.7727 - loss: 0.5247
Epoch 2699/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - accuracy: 0.7727 - loss: 0.5247
Epoch 2700/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - accuracy: 0.7727 - loss: 0.5247
Epoch 2701/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - accuracy: 0.7727 - loss: 0.5246
Epoch 2702/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - accuracy: 0.7727 - loss: 0.5246
Epoch 2703/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 62ms/step - accuracy: 0.7727 - loss: 0.5246
Epoch 2704/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.7727 - loss: 0.5245
Epoch 2705/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - accuracy: 0.7727 - loss: 0.5245
Epoch 2706/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 75ms/step - accuracy: 0.7727 - loss: 0.5245
Epoch 2707/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 0.7727 - loss: 0.5244
Epoch 2708/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 64ms/step - accuracy: 0.7727 - loss: 0.5244
Epoch 2709/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - accuracy: 0.7727 - loss: 0.5243
Epoch 2710/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.7727 - loss: 0.5243
Epoch 2711/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - accuracy: 0.7727 - loss: 0.5243
Epoch 2712/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - accuracy: 0.7727 - loss: 0.5242
Epoch 2713/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 63ms/step - accuracy: 0.7727 - loss: 0.5242
Epoch 2714/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 0.7727 - loss: 0.5242
Epoch 2715/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - accuracy: 0.7727 - loss: 0.5241
Epoch 2716/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.7727 - loss: 0.5241
Epoch 2717/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 0.7727 - loss: 0.5241
Epoch 2718/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.7727 - loss: 0.5240
Epoch 2719/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.7727 - loss: 0.5240
Epoch 2720/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 69ms/step - accuracy: 0.7727 - loss: 0.5239
Epoch 2721/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 135ms/step - accuracy: 0.7727 - loss: 0.5239
Epoch 2722/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 134ms/step - accuracy: 0.7727 - loss: 0.5239
Epoch 2723/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 62ms/step - accuracy: 0.7727 - loss: 0.5238
Epoch 2724/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - accuracy: 0.7727 - loss: 0.5238
Epoch 2725/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - accuracy: 0.7727 - loss: 0.5238
Epoch 2726/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 0.7727 - loss: 0.5237
Epoch 2727/5000

In [14]:
model.evaluate(X_test_scaled,y_test)

1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 505ms/step - accuracy: 1.0000 - loss: 0.3550

[0.35497763752937317, 1.0]

In [15]:
X_test_scaled

    affordibility   age
2               1  0.47
10              1  0.18
21              0  0.26
11              1  0.28
14              1  0.49
9               1  0.61

In [16]:
y_test

2     1
10    0
21    0
11    0
14    1
9     1
Name: bought_insurance, dtype: int64

In [17]:
predictions=model.predict(X_test_scaled)
predictions

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 270ms/step

array([[0.7054848 ],
       [0.3556957 ],
       [0.16827835],
       [0.4780119 ],
       [0.7260696 ],
       [0.8294983 ]], dtype=float32)

In [18]:
y_actual_predictions=(predictions>=0.5).astype(int)
y_actual_predictions

array([[1],
       [0],
       [0],
       [0],
       [1],
       [1]])

In [19]:
#knowing the weights
coef,intercept=model.get_weights()
coef,intercept

(array([[1.408652 ],
        [5.0608625]], dtype=float32),
 array([-2.9137027], dtype=float32))

implementing in python

In [20]:
def sigmoid(x):
 import math
 return 1/(1+math.exp(-x))
sigmoid(16)

0.9999998874648379

In [21]:
def prediction_function(age,affordability):
  weighted_sum=coef[0]*age+coef[1]*affordability+intercept
  return sigmoid(weighted_sum)

In [22]:
prediction_function(.47,1)

<ipython-input-20-41872bf8f8af>:3: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  return 1/(1+math.exp(-x))

0.9431723630699127

In [23]:
def logloss(y_true,y_actual_predictions):
  epsilon=1e-15
  y_predicted_new=np.clip(y_actual_predictions,epsilon,1-epsilon)
  return -np.mean(y_true*np.log(y_predicted_new)+(1-y_true)*np.log(1-y_predicted_new))

In [26]:
#it gives the sigmoid of the entire array
def sigmoid_numpy(X):
  return 1/(1+np.exp(-X))

sigmoid_numpy(np.array([12,0,1]))

array([0.99999386, 0.5       , 0.73105858])

In [44]:
def gradient_descent(age,affordability,y_true,epochs,loss_thresold=0.4631):
  w1=w2=1
  bias=0
  rate=0.1
  n=len(age)
  for i in range(epochs):
    weighted_sum= w1*age+w2*affordability+bias
    y_predicted=sigmoid_numpy(weighted_sum)
    loss=logloss(y_true,y_predicted)
    w1d=(1/n)*np.dot(np.transpose(age),(y_predicted-y_true))
    w2d=(1/n)*np.dot(np.transpose(affordability),(y_predicted-y_true))
    bias=np.mean(y_predicted-y_true)
    w1=w1-rate*w1d
    w2=w2-rate*w2d
    print(f'epoch:{i},w1:{w1},w2:{w2},bias:{bias},loss:{loss}')
    if loss<=loss_thresold:
      break
  return w1,w2,bias

In [45]:
gradient_descent(X_train_scaled['age'],X_train_scaled['affordibility'],y_train,1000)

epoch:0,w1:0.9949815266940354,w2:0.9896696250789058,bias:0.22683735472737165,loss:0.7113403233723417
epoch:1,w1:0.9884526125464794,w2:0.9773435933265646,bias:0.2660212531686501,loss:0.7658470543639112
epoch:2,w1:0.9817316862045118,w2:0.9648095514835985,bias:0.2711467907421431,loss:0.7744067241510453
epoch:3,w1:0.9750411205661081,w2:0.9523626196540338,bias:0.2704992735780208,loss:0.7737785814297374
epoch:4,w1:0.9684183566228521,w2:0.9400525963188087,bias:0.26888019088784143,loss:0.7716178237443305
epoch:5,w1:0.96186973675356,w2:0.9278880413546495,bias:0.26709724126214146,loss:0.7692413368046052
epoch:6,w1:0.9553963311235584,w2:0.9158704828139532,bias:0.2652872323228762,loss:0.7668695016053279
epoch:7,w1:0.9489982936695974,w2:0.9040002059198157,bias:0.2634738767272211,loss:0.7645389701669295
epoch:8,w1:0.9426756014958794,w2:0.8922772398164557,bias:0.26166170337970035,loss:0.7622555892512513
epoch:9,w1:0.9364281812775919,w2:0.8807015270377698,bias:0.25985196366113567,loss:0.7600199984472134
epoch:10,w1:0.9302559311102514,w2:0.8692729530171543,bias:0.2580453425315105,loss:0.757831938486063
epoch:11,w1:0.9241587244334311,w2:0.8579913515248228,bias:0.2562424230802032,loss:0.7556909814332403
epoch:12,w1:0.9181364108845537,w2:0.8468565059869424,bias:0.2544437661037555,loss:0.7535966557297236
epoch:13,w1:0.9121888166461816,w2:0.8358681501430962,bias:0.2526499233022464,loss:0.7515484682442511
epoch:14,w1:0.9063157447313289,w2:0.8250259686431832,bias:0.2508614389720441,loss:0.7495459087017978
epoch:15,w1:0.9005169752836777,w2:0.8143295976874382,bias:0.24907884970951552,loss:0.7475884510914796
epoch:16,w1:0.8947922659053303,w2:0.8037786257259331,bias:0.24730268378703668,loss:0.7456755545660947
epoch:17,w1:0.88914135201338,w2:0.7933725942183958,bias:0.24553346049442004,loss:0.7438066642664164
epoch:18,w1:0.883563947224509,w2:0.7831109984522995,bias:0.24377168949890013,loss:0.741981212143592
epoch:19,w1:0.8780597437664055,w2:0.7729932884165538,bias:0.2420178702343563,loss:0.7401986177903641
epoch:20,w1:0.8726284129146579,w2:0.7630188697279153,bias:0.24027249132278025,loss:0.7384582892808557
epoch:21,w1:0.867269605453725,w2:0.753187104607112,bias:0.23853603002947874,loss:0.736759624016759
epoch:22,w1:0.8619829521605264,w2:0.7434973129015793,bias:0.23680895175308694,loss:0.7351020095774478
epoch:23,w1:0.8567680643091585,w2:0.7339487731516303,bias:0.23509170955124847,loss:0.7334848245715168
epoch:24,w1:0.8516245341952084,w2:0.7245407236968204,bias:0.23338474370263151,loss:0.731907439487303
epoch:25,w1:0.8465519356781142,w2:0.7152723638192201,bias:0.23168848130577702,loss:0.7303692175400051
epoch:26,w1:0.8415498247399993,w2:0.706142854920283,bias:0.23000333591510055,loss:0.7288695155130949
epoch:27,w1:0.8366177400594031,w2:0.6971513217279781,bias:0.2283297072142016,loss:0.7274076845918082
epoch:28,w1:0.8317552035983212,w2:0.6882968535308586,bias:0.22666798072647154,loss:0.7259830711865894
epoch:29,w1:0.826961721200976,w2:0.6795785054357485,bias:0.22501852756283547,loss:0.724595017744482
epoch:30,w1:0.8222367832027478,w2:0.6709952996457623,bias:0.22338170420630934,loss:0.723242863546555
epoch:31,w1:0.8175798650477117,w2:0.6625462267554069,bias:0.22175785233291492,loss:0.7219259454895817
epoch:32,w1:0.8129904279132476,w2:0.654230247059571,bias:0.22014729866835883,loss:0.7206435988503045
epoch:33,w1:0.8084679193402217,w2:0.6460462918732702,bias:0.21855035487975522,loss:0.7193951580307502
epoch:34,w1:0.804011773867266,w2:0.6379932648590874,bias:0.21696731750155698,loss:0.7181799572831765
epoch:35,w1:0.7996214136677242,w2:0.6300700433593353,bias:0.21539846789475267,loss:0.7169973314133811
epoch:36,w1:0.7952962491878716,w2:0.622275479730057,bias:0.21384407223828908,loss:0.7158466164612112
epoch:37,w1:0.7910356797850638,w2:0.6146084026740822,bias:0.21230438155159162,loss:0.7147271503572659
epoch:38,w1:0.7868390943645195,w2:0.6070676185704621,bias:0.21077963174697947,loss:0.7136382735548976
epoch:39,w1:0.7827058720134916,w2:0.5996519127977205,bias:0.20927004371070324,loss:0.7125793296367547
epoch:40,w1:0.7786353826316413,w2:0.5923600510484748,bias:0.207775823411278,loss:0.7115496658952329
epoch:41,w1:0.7746269875564818,w2:0.5851907806331044,bias:0.20629716203373488,loss:0.7105486338863266
epoch:42,w1:0.7706800401828208,w2:0.5781428317702673,bias:0.20483423613837803,loss:0.7095755899564902
epoch:43,w1:0.7667938865751907,w2:0.5712149188621964,bias:0.2033872078426058,loss:0.7086298957422364
epoch:44,w1:0.762967866072317,w2:0.5644057417528353,bias:0.2019562250243318,loss:0.7077109186423093
epoch:45,w1:0.7592013118827367,w2:0.5577139869670035,bias:0.2005414215455347,loss:0.7068180322623717
epoch:46,w1:0.7554935516707416,w2:0.551138328928915,bias:0.19914291749445887,loss:0.7059506168322598
epoch:47,w1:0.751843908131886,w2:0.5446774311585018,bias:0.1977608194449929,loss:0.7051080595959333
epoch:48,w1:0.7482516995573558,w2:0.538329947444125,bias:0.19639522073176463,loss:0.7042897551743583
epoch:49,w1:0.7447162403865628,w2:0.5320945229903868,bias:0.19504620173950785,loss:0.7034951059016297
epoch:50,w1:0.7412368417473839,w2:0.5259697955398781,bias:0.19371383020528113,loss:0.7027235221347221
epoch:51,w1:0.7378128119835289,w2:0.519954396467824,bias:0.19239816153214503,loss:0.7019744225373286
epoch:52,w1:0.7344434571685751,w2:0.5140469518487095,bias:0.19109923911294183,loss:0.7012472343383104
epoch:53,w1:0.7311280816062657,w2:0.5082460834940836,bias:0.18981709466285526,loss:0.7005413935653385
epoch:54,w1:0.7278659883167238,w2:0.5025504099608545,bias:0.18855174855947368,loss:0.6998563452543625
epoch:55,w1:0.7246564795082855,w2:0.4969585475294989,bias:0.18730321018912308,loss:0.6991915436355822
epoch:56,w1:0.7214988570347096,w2:0.49146911115171193,bias:0.1860714782982839,loss:0.6985464522966487
epoch:57,w1:0.7183924228375673,w2:0.486080715367127,bias:0.18485654134895813,loss:0.6979205443238404
epoch:58,w1:0.7153364793736643,w2:0.48079197518883016,bias:0.18365837787690192,loss:0.697313302422007
epoch:59,w1:0.712330330027392,w2:0.475601506957485,bias:0.1824769568516955,loss:0.6967242190140811
epoch:60,w1:0.7093732795079462,w2:0.47050792916397144,bias:0.18131223803767485,loss:0.6961527963209887
epoch:61,w1:0.7064646342313928,w2:0.4655098632405231,bias:0.18016417235480459,loss:0.695598546422796
epoch:62,w1:0.7036037026875976,w2:0.46060593432042507,bias:0.17903270223862855,loss:0.6950609913019447
epoch:63,w1:0.7007897957920709,w2:0.45579477196640583,bias:0.17791776199848727,loss:0.694539662869428
epoch:64,w1:0.6980222272228138,w2:0.4510750108679245,bias:0.17681927817324922,loss:0.6940341029747712
epoch:65,w1:0.695300313742282,w2:0.4464452915076166,bias:0.17573716988385468,loss:0.6935438634006609
epoch:66,w1:0.6926233755046104,w2:0.44190426079721895,bias:0.17467134918202565,loss:0.6930685058430854
epoch:67,w1:0.6899907363482712,w2:0.4374505726833486,bias:0.17362172139454785,loss:0.6926076018778161
epoch:68,w1:0.687401724074359,w2:0.4330828887235568,bias:0.17258818546258115,loss:0.6921607329140671
epoch:69,w1:0.6848556707107195,w2:0.4287998786331262,bias:0.17157063427550473,loss:0.6917274901361453
epoch:70,w1:0.6823519127621612,w2:0.4246002208031155,bias:0.17056895499885089,loss:0.6913074744338945
epoch:71,w1:0.6798897914470006,w2:0.42048260279019567,bias:0.16958302939592937,loss:0.6909002963227117
epoch:72,w1:0.6774686529202153,w2:0.4164457217788501,bias:0.16861273414278555,loss:0.6905055758539024
epoch:73,w1:0.675087848483488,w2:0.4124882850165407,bias:0.16765794113618251,loss:0.6901229425161137
epoch:74,w1:0.6727467347824384,w2:0.40860901022246676,bias:0.16671851779433375,loss:0.6897520351285644
epoch:75,w1:0.670444673991352,w2:0.4048066259705626,bias:0.16579432735015517,loss:0.6893925017267682
epoch:76,w1:0.6681810339857216,w2:0.40107987204740014,bias:0.16488522913683956,loss:0.6890439994414223
epoch:77,w1:0.6659551885029272,w2:0.3974274997856745,bias:0.16399107886559366,loss:0.6887061943711017
epoch:78,w1:0.6637665172913845,w2:0.39384827237396475,bias:0.16311172889540845,loss:0.6883787614493894
epoch:79,w1:0.6616144062484973,w2:0.39034096514346966,bias:0.16224702849476552,loss:0.6880613843070251
epoch:80,w1:0.6594982475477541,w2:0.3869043658324249,bias:0.16139682409521103,loss:0.6877537551296512
epoch:81,w1:0.6574174397553094,w2:0.3835372748289125,bias:0.16056095953675478,loss:0.6874555745116903
epoch:82,w1:0.6553713879363935,w2:0.3802385053927756,bias:0.15973927630507834,loss:0.6871665513068741
epoch:83,w1:0.6533595037518933,w2:0.37700688385734993,bias:0.15893161376055748,loss:0.6868864024759124
epoch:84,w1:0.651381205545448,w2:0.37384124981172306,bias:0.1581378093591278,loss:0.6866148529317677
epoch:85,w1:0.6494359184213988,w2:0.37074045626422786,bias:0.15735769886503873,loss:0.6863516353829695
epoch:86,w1:0.6475230743139339,w2:0.3677033697878707,bias:0.15659111655556351,loss:0.6860964901753875
epoch:87,w1:0.6456421120477623,w2:0.36472887064838944,bias:0.1558378954177444,loss:0.685849165132852
epoch:88,w1:0.6437924773906509,w2:0.36181585291562657,bias:0.15509786733727066,loss:0.6856094153969818
epoch:89,w1:0.6419736230981502,w2:0.3589632245588948,bias:0.1543708632795984,loss:0.68537700326657
epoch:90,w1:0.6401850089508341,w2:0.3561699075270011,bias:0.15365671346343393,loss:0.6851516980368412
epoch:91,w1:0.6384261017843703,w2:0.3534348378135844,bias:0.15295524752671294,loss:0.6849332758388802
epoch:92,w1:0.6366963755127341,w2:0.35075696550840946,bias:0.15226629468521616,loss:0.6847215194795089
epoch:93,w1:0.6349953111448706,w2:0.3481352548352474,bias:0.1515896838839727,loss:0.684516218281868
epoch:94,w1:0.6333223967951073,w2:0.34556868417695863,bias:0.15092524394160622,loss:0.6843171679269392
epoch:95,w1:0.6316771276876066,w2:0.34305624608838103,bias:0.1502728036877879,loss:0.6841241702962274
epoch:96,w1:0.6300590061551484,w2:0.34059694729761086,bias:0.1496321920939633,loss:0.6839370333157997
epoch:97,w1:0.6284675416325183,w2:0.3381898086962492,bias:0.14900323839752552,loss:0.6837555708018699
epoch:98,w1:0.6269022506447752,w2:0.3358338653191722,bias:0.14838577221960997,loss:0.6835796023080877
epoch:99,w1:0.6253626567906629,w2:0.3335281663143666,bias:0.1477796236766882,loss:0.6834089529746861
epoch:100,w1:0.6238482907214208,w2:0.33127177490335785,bias:0.14718462348614075,loss:0.6832434533796273
epoch:101,w1:0.6223586901152444,w2:0.3290637683327415,bias:0.1466006030659896,loss:0.6830829393918586
epoch:102,w1:0.6208933996476382,w2:0.3269032378173132,bias:0.14602739462897144,loss:0.6829272520267973
epoch:103,w1:0.6194519709578935,w2:0.32478928847527677,bias:0.14546483127113302,loss:0.682776237304132
epoch:104,w1:0.6180339626119181,w2:0.3227210392559945,bias:0.14491274705512922,loss:0.6826297461080292
epoch:105,w1:0.6166389400616387,w2:0.3206976228607269,bias:0.14437097708840357,loss:0.6824876340498146
epoch:106,w1:0.6152664756011853,w2:0.3187181856567957,bias:0.14383935759642863,loss:0.6823497613331931
epoch:107,w1:0.6139161483200636,w2:0.31678188758558695,bias:0.1433177259911841,loss:0.6822159926220581
epoch:108,w1:0.6125875440535112,w2:0.31488790206479594,bias:0.14280592093504507,loss:0.6820861969109345
epoch:109,w1:0.6112802553302279,w2:0.31303541588530215,bias:0.1423037824002533,loss:0.6819602473980869
epoch:110,w1:0.6099938813176617,w2:0.3112236291030459,bias:0.1418111517241403,loss:0.6818380213613234
epoch:111,w1:0.6087280277650278,w2:0.30945175492626514,bias:0.1413278716602677,loss:0.6817194000365097
epoch:112,w1:0.6074823069442258,w2:0.30771901959843606,bias:0.14085378642564841,loss:0.6816042684988068
epoch:113,w1:0.6062563375888214,w2:0.30602466227724784,bias:0.14038874174420768,loss:0.6814925155466398
epoch:114,w1:0.6050497448312435,w2:0.30436793490992753,bias:0.1399325848866402,loss:0.6813840335883915
epoch:115,w1:0.6038621601383487,w2:0.3027481021052182,bias:0.13948516470681557,loss:0.6812787185318233
epoch:116,w1:0.602693221245493,w2:0.30116444100230094,bias:0.13904633167488073,loss:0.6811764696762022
epoch:117,w1:0.601542572089249,w2:0.29961624113693763,bias:0.13861593790720458,loss:0.6810771896071285
epoch:118,w1:0.6004098627388978,w2:0.2981028043051001,bias:0.13819383719330522,loss:0.6809807840940364
epoch:119,w1:0.5992947493268204,w2:0.29662344442433886,bias:0.13777988501989705,loss:0.680887161990348
epoch:120,w1:0.5981968939779064,w2:0.29517748739313276,bias:0.1373739385921919,loss:0.6807962351362526
epoch:121,w1:0.5971159647380954,w2:0.29376427094845076,bias:0.13697585685258123,loss:0.6807079182640817
epoch:122,w1:0.5960516355021561,w2:0.2923831445217442,bias:0.13658550049682708,loss:0.680622128906245
epoch:123,w1:0.5950035859408085,w2:0.29103346909357913,bias:0.13620273198788097,loss:0.6805387873056948
epoch:124,w1:0.5939715014272846,w2:0.2897146170471076,bias:0.1358274155674498,loss:0.6804578163288788
epoch:125,w1:0.592955072963423,w2:0.2884259720205657,bias:0.13545941726542096,loss:0.6803791413811419
epoch:126,w1:0.5919539971053823,w2:0.2871669287589783,bias:0.1350986049072572,loss:0.6803026903245378
epoch:127,w1:0.5909679758890605,w2:0.28593689296524044,bias:0.13474484811946652,loss:0.6802283933980053
epoch:128,w1:0.5899967167552964,w2:0.2847352811507355,bias:0.13439801833324933,loss:0.6801561831398667
epoch:129,w1:0.589039932474931,w2:0.28356152048564387,bias:0.1340579887864212,loss:0.680085994312602
epoch:130,w1:0.5880973410737972,w2:0.2824150486490854,bias:0.13372463452370653,loss:0.680017763829855
epoch:131,w1:0.5871686657577065,w2:0.2812953136792318,bias:0.13339783239549302,loss:0.6799514306856237
epoch:132,w1:0.5862536348374964,w2:0.2802017738235179,bias:0.13307746105513635,loss:0.6798869358855859
epoch:133,w1:0.5853519816541958,w2:0.27913389738907324,bias:0.13276340095489797,loss:0.6798242223805167
epoch:134,w1:0.5844634445043679,w2:0.2780911625934867,bias:0.13245553434059756,loss:0.6797632350017458
epoch:135,w1:0.583587766565681,w2:0.27707305741601324,bias:0.13215374524505832,loss:0.6797039203986114
epoch:136,w1:0.5827246958227575,w2:0.27607907944932214,bias:0.13185791948041883,loss:0.6796462269778567
epoch:137,w1:0.5818739849933486,w2:0.27510873575188194,bias:0.1315679446293836,loss:0.6795901048449283
epoch:138,w1:0.5810353914548766,w2:0.2741615427010707,bias:0.13128371003548012,loss:0.6795355057471233
epoch:139,w1:0.5802086771713876,w2:0.27323702584709353,bias:0.13100510679238953,loss:0.6794823830185392
epoch:140,w1:0.5793936086209514,w2:0.27233471976778617,bias:0.1307320277324113,loss:0.6794306915267834
epoch:141,w1:0.5785899567235441,w2:0.27145416792437493,bias:0.13046436741412437,loss:0.679380387621389
epoch:142,w1:0.5777974967694478,w2:0.27059492251826145,bias:0.13020202210930024,loss:0.6793314290838977
epoch:143,w1:0.577016008348196,w2:0.26975654434889385,bias:0.1299448897891243,loss:0.6792837750795591
epoch:144,w1:0.5762452752780951,w2:0.2689386026727819,bias:0.1296928701097766,loss:0.679237386110604
epoch:145,w1:0.5754850855363471,w2:0.26814067506370987,bias:0.1294458643974226,loss:0.6791922239710494
epoch:146,w1:0.5747352311897983,w2:0.26736234727419567,bias:0.12920377563266106,loss:0.6791482517029853
epoch:147,w1:0.5739955083263355,w2:0.26660321309824203,bias:0.1289665084344753,loss:0.679105433554308
epoch:148,w1:0.5732657169869514,w2:0.26586287423542043,bias:0.12873396904372986,loss:0.6790637349378533
epoch:149,w1:0.5725456610984965,w2:0.26514094015632594,bias:0.12850606530625439,loss:0.6790231223918888
epoch:150,w1:0.5718351484071349,w2:0.2644370279694372,bias:0.1282827066555541,loss:0.678983563541926
epoch:151,w1:0.5711339904125199,w2:0.26375076228941263,bias:0.1280638040951832,loss:0.6789450270638124
epoch:152,w1:0.570442002302702,w2:0.2630817751068507,bias:0.1278492701808174,loss:0.6789074826480631
epoch:153,w1:0.5697590028897827,w2:0.2624297056595393,bias:0.1276390190020583,loss:0.6788709009653959
epoch:154,w1:0.5690848145463239,w2:0.2617942003052167,bias:0.1274329661640021,loss:0.6788352536334327
epoch:155,w1:0.5684192631425247,w2:0.2611749123958631,bias:0.12723102876860268,loss:0.6788005131845272
epoch:156,w1:0.5677621779841707,w2:0.26057150215354047,bias:0.12703312539585704,loss:0.6787666530346907
epoch:157,w1:0.5671133917513661,w2:0.2599836365477951,bias:0.12683917608484133,loss:0.6787336474535737
epoch:158,w1:0.5664727404380527,w2:0.2594109891746349,bias:0.12664910231462148,loss:0.6787014715354737
epoch:159,w1:0.5658400632923222,w2:0.25885324013709243,bias:0.12646282698506423,loss:0.6786701011713365
epoch:160,w1:0.5652152027575243,w2:0.25831007592738153,bias:0.12628027439757006,loss:0.678639513021718
epoch:161,w1:0.5645980044141758,w2:0.2577811893106539,bias:0.126101370235751,loss:0.6786096844906742
epoch:162,w1:0.5639883169226706,w2:0.2572662792103605,bias:0.12592604154607176,loss:0.6785805937005515
epoch:163,w1:0.5633859919667938,w2:0.25676505059522037,bias:0.1257542167184755,loss:0.6785522194676464
epoch:164,w1:0.5627908841980396,w2:0.25627721436779843,bias:0.12558582546701044,loss:0.6785245412787053
epoch:165,w1:0.5622028511807329,w2:0.2558024872546919,bias:0.12542079881047538,loss:0.678497539268238
epoch:166,w1:0.5616217533379544,w2:0.25534059169832385,bias:0.12525906905309964,loss:0.6784711941966172
epoch:167,w1:0.5610474538982666,w2:0.2548912557503407,bias:0.12510056976527212,loss:0.6784454874289364
epoch:168,w1:0.5604798188432396,w2:0.25445421296661014,bias:0.12494523576433428,loss:0.6784204009146042
epoch:169,w1:0.5599187168557734,w2:0.2540292023038133,bias:0.124793003095449,loss:0.6783959171676454
epoch:170,w1:0.5593640192692141,w2:0.25361596801762554,bias:0.12464380901255868,loss:0.6783720192476878
epoch:171,w1:0.5588156000172588,w2:0.25321425956247773,bias:0.12449759195944314,loss:0.6783486907416125
epoch:172,w1:0.5582733355846476,w2:0.2528238314928904,bias:0.1243542915508884,loss:0.6783259157458423
epoch:173,w1:0.5577371049586352,w2:0.25244444336637095,bias:0.12421384855397631,loss:0.6783036788492472
epoch:174,w1:0.5572067895812384,w2:0.2520758596478639,bias:0.12407620486950394,loss:0.6782819651166465
epoch:175,w1:0.5566822733022554,w2:0.25171784961574356,bias:0.12394130351354114,loss:0.6782607600728869
epoch:176,w1:0.556163442333048,w2:0.2513701872693377,bias:0.12380908859913496,loss:0.678240049687476
epoch:177,w1:0.5556501852010834,w2:0.2510326512379693,bias:0.1236795053181669,loss:0.6782198203597513
epoch:178,w1:0.5551423927052279,w2:0.25070502469150463,bias:0.12355249992337138,loss:0.6782000589045691
epoch:179,w1:0.5546399578717859,w2:0.25038709525239344,bias:0.12342801971051941,loss:0.6781807525384916
epoch:180,w1:0.5541427759112776,w2:0.2500786549091878,bias:0.12330601300077525,loss:0.6781618888664558
epoch:181,w1:0.5536507441759483,w2:0.2497794999315252,bias:0.12318642912322976,loss:0.6781434558689097
epoch:182,w1:0.5531637621180013,w2:0.24948943078656133,bias:0.12306921839761564,loss:0.6781254418893958
epoch:183,w1:0.5526817312485478,w2:0.2492082520568369,bias:0.12295433211720862,loss:0.6781078356225692
epoch:184,w1:0.5522045550972648,w2:0.24893577235956363,bias:0.12284172253191833,loss:0.6780906261026323
epoch:185,w1:0.5517321391727547,w2:0.2486718042673134,bias:0.12273134283157269,loss:0.6780738026921743
epoch:186,w1:0.5512643909235967,w2:0.24841616423009408,bias:0.12262314712939784,loss:0.6780573550713976
epoch:187,w1:0.5508012197000844,w2:0.24816867249879657,bias:0.12251709044569749,loss:0.6780412732277237
epoch:188,w1:0.5503425367166384,w2:0.2479291530499956,bias:0.12241312869173288,loss:0.678025547445754
epoch:189,w1:0.5498882550148871,w2:0.24769743351208834,bias:0.12231121865380615,loss:0.6780101682975878
epoch:190,w1:0.5494382894274085,w2:0.24747334509275337,bias:0.12221131797754797,loss:0.6779951266334704
epoch:191,w1:0.5489925565421213,w2:0.2472567225077133,bias:0.12211338515241205,loss:0.6779804135727695
epoch:192,w1:0.5485509746673203,w2:0.24704740391078384,bias:0.12201737949637606,loss:0.6779660204952642
epoch:193,w1:0.5481134637973443,w2:0.24684523082519197,bias:0.12192326114085122,loss:0.6779519390327349
epoch:194,w1:0.5476799455788705,w2:0.2466500480761462,bias:0.12183099101580043,loss:0.6779381610608451

(np.float64(0.4137448490021443),
 np.float64(0.2949001990432335),
 np.float64(0.11447271766124571))

In [43]:
coef,intercept

(array([[1.408652 ],
        [5.0608625]], dtype=float32),
 array([-2.9137027], dtype=float32))